# master-playbook.yml
- name: Prepare Node and Deploy Firedancer
  hosts: all
  become: yes
  tasks:
    # Your tasks for updating and upgrading the system here

- name: Set up Disks
  import_playbook: ./playbooks/disk-setup.yml

- name: Deploy Firedancer
  import_playbook: ./playbooks/deploy.yml