# master-playbook.yml
- name: Prepare Node and Deploy Firedancer
  hosts: all
  become: yes
  tasks:

#- name: Upgrade System
#  import_playbook: ./playbooks/upgrade.yml
  
- name: Set up Disks
  import_playbook: ./playbooks/disk-setup.yml

- name: Deploy Firedancer
  import_playbook: ./playbooks/firedancer.yml

- name: Install Solana CLI
  import_playbook: ./playbooks/solana-install.yml

- name: Keys and Airdrop
  import_playbook: ./playbooks/solana-keys.yml
