---
- name: Setup Firedancer Environment
  hosts: all
  become: yes
  vars:
    user_home: "/home/{{ ansible_user }}"
    firedancer_repo: "https://github.com/firedancer-io/firedancer.git"
    firedancer_dir: "{{ user_home }}/firedancer"
    ledger_mount_point: "/srv/solana"
    script_path: "/tmp/build.sh"  # Temporary path for the script on the remote server


  tasks:
    - name: Install the latest security updates
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - gcc
          - clang
          - git
          - make
          - net-tools
        state: present

    - name: Download Rust installation script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: '0755'

    - name: Run Rust installation script
      ansible.builtin.shell: sh /tmp/rustup.sh -y
      args:
        creates: ~/.cargo/bin/rustc

    - name: Clone firedancer
      git:
        repo: "{{ firedancer_repo }}"
        dest: "{{ firedancer_dir }}"
        recursive: yes

    - name: Copy build script to remote server
      copy:
        src: ../files/build.sh
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Execute build script
      shell: "{{ script_path }}"
      args:
        chdir: "{{ firedancer_dir }}"  # Execute the script in the firedancer directory
        executable: /bin/bash

    - name: Copy firedancer to your path
      copy:
        src: "{{ firedancer_dir }}/build/native/gcc/bin/fdctl"
        dest: "/usr/local/bin/fdctl"
        remote_src: yes
        mode: '0755'

    - name: Create a firedancer user
      user:
        name: firedancer

    - name: Add firedancer to sudoers
      lineinfile:
        path: /etc/sudoers
        line: 'firedancer ALL=(ALL) NOPASSWD:ALL'

    - name: Ensure ledger mount point exists and set ownership
      file:
        path: "{{ ledger_mount_point }}"
        owner: firedancer
        group: firedancer
        state: directory
        mode: '0755'

    - name: Copy config file for firedancer user
      copy:
        src: "./files/config.yml"
        dest: "{{ user_home }}/config.yml"
        owner: firedancer
        group: firedancer
        mode: '0644'

    - name: Create start script
      block:
        - file:
            path: "{{ user_home }}/bin"
            state: directory
        - copy:
            dest: "{{ user_home }}/bin/validator.sh"
            content: |
              #!/usr/bin/env bash
              sudo fdctl configure init all --config {{ user_home }}/config.toml
              sudo fdctl run --config {{ user_home }}/config.toml
            mode: '0755'

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/firedancer.service
        content: |
          [Unit]
          Description=Firedancer Solana Validator
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          Type=simple
          Restart=always
          RestartSec=1
          User=firedancer
          LimitNOFILE=1000000
          LogRateLimitIntervalSec=0
          ExecStart={{ user_home }}/bin/validator.sh

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start firedancer service
      systemd:
        name: firedancer
        enabled: yes
