---
- name: Setup Firedancer Environment
  hosts: all
  become: yes
  vars:
    user_home: "/home/{{ ansible_user }}"
    firedancer_repo: "https://github.com/firedancer-io/firedancer.git"
    firedancer_dir: "{{ user_home }}/firedancer"
    ledger_device: "/dev/nvme0n1"
    ledger_mount_point: "/mnt/ledger"

  tasks:
    - name: Install the latest security updates
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - gcc
          - clang
          - git
          - make
          - net-tools
        state: present

    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Clone firedancer
      git:
        repo: "{{ firedancer_repo }}"
        dest: "{{ firedancer_dir }}"
        recursive: yes

    - name: Install firedancer
      shell: |
        cd {{ firedancer_dir }}
        FD_AUTO_INSTALL_PACKAGES=1 ./deps.sh check install
        make -j fdctl solana

    - name: Symlink firedancer to your path (Optional)
      file:
        src: "{{ firedancer_dir }}/build/native/gcc/bin/fdctl"
        dest: "/usr/local/bin/fdctl"
        state: link

    - name: Create a firedancer user
      user:
        name: firedancer

    - name: Add firedancer to sudoers
      lineinfile:
        path: /etc/sudoers
        line: 'firedancer ALL=(ALL) NOPASSWD:ALL'

    - name: Configure Ledger
      block:
        - shell: mkfs -t ext4 {{ ledger_device }}
        - file:
            path: "{{ ledger_mount_point }}"
            state: directory
        - shell: chown -R firedancer:firedancer {{ ledger_mount_point }}
        - shell: mount {{ ledger_device }} {{ ledger_mount_point }}

    - name: Switch to firedancer user and setup config
      block:
        - shell: |
            su - firedancer
            echo 'user = "firedancer"' > {{ user_home }}/config.toml
            # ... add the rest of the config here ...
          args:
            executable: /bin/bash

    - name: Create start script
      block:
        - file:
            path: "{{ user_home }}/bin"
            state: directory
        - copy:
            dest: "{{ user_home }}/bin/validator.sh"
            content: |
              #!/usr/bin/env bash
              sudo fdctl configure init all --config {{ user_home }}/config.toml
              sudo fdctl run --config {{ user_home }}/config.toml
            mode: 0755

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/firedancer.service
        content: |
          [Unit]
          Description=Firedancer Solana
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          Type=simple
          Restart=always
          RestartSec=1
          User=firedancer
          LimitNOFILE=1000000
          LogRateLimitIntervalSec=0
          ExecStart={{ user_home }}/bin/validator.sh

          [Install]
          WantedBy=multi-user.target

    - name: Start firedancer service
      systemd:
        name: firedancer
        enabled: yes
        state: started