---
- name: Deploy and execute solana-install.sh script
  hosts: all
  become: yes

  tasks:
    - name: Copy solana-install.sh to remote server
      copy:
        src: "../files/solana-install.sh"
        dest: "/tmp/solana-install.sh"
        mode: '0755'  # Ensure the script is executable

    - name: Execute solana-install.sh on remote server
      shell: "/tmp/solana-install.sh"
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"  # Execute in the user's home directory

    - name: Find Solana binaries
      find:
        paths: "/root/.local/share/solana/install/active_release/bin"
        file_type: file
      register: solana_binaries  # This variable will store the result of the find module

    - name: Copy Solana binaries to /usr/local/bin
      copy:
        src: "{{ item.path }}"
        dest: "/usr/local/bin/{{ item.path | basename }}"
        remote_src: yes  # Specifies that the source is on the remote machine
        mode: '0755'  # Ensure the binaries are executable
      with_items: "{{ solana_binaries.files }}"
      loop_control:
        loop_var: item