- name: Generate Solana keypairs and set ownership
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Generate validator keypair
      shell: solana-keygen new --no-bip39-passphrase --outfile validator-keypair.json
      args:
        chdir: /home/firedancer/
        creates: /home/firedancer/validator-keypair.json

    - name: Generate vote account keypair
      shell: solana-keygen new --no-bip39-passphrase --outfile vote-account-keypair.json
      args:
        chdir: /home/firedancer/
        creates: /home/firedancer/vote-account-keypair.json

    - name: Generate authorized withdrawer keypair
      shell: solana-keygen new --no-bip39-passphrase --outfile authorized-withdrawer-keypair.json
      args:
        chdir: /home/firedancer/
        creates: /home/firedancer/authorized-withdrawer-keypair.json

    - name: Set keypair permissions
      file:
        path: "{{ item }}"
        mode: 0600
        owner: firedancer
        group: firedancer
      with_items:
        - /home/firedancer/validator-keypair.json
        - /home/firedancer/vote-account-keypair.json
        - /home/firedancer/authorized-withdrawer-keypair.json

    - name: Change ownership of /home/firedancer to firedancer user and group
      file:
        path: /home/firedancer
        state: directory
        recurse: yes
        owner: firedancer
        group: firedancer

    - name: Change directory to firedancer home and run a command
      command:
        cmd: solana config set --keypair validator-keypair.json
        chdir: /home/firedancer

    - name: Airdrop SOL to validator keypair
      command:
        cmd: solana airdrop 1 validator-keypair.json
        chdir: /home/firedancer/
      register: airdrop_result
      ignore_errors: yes

    - name: Check airdrop result
      debug:
        msg: "{{ airdrop_result.stdout_lines }}"
      when: airdrop_result is defined and airdrop_result.rc == 0

    - name: Show airdrop error if failed
      debug:
        msg: "{{ airdrop_result.stderr_lines }}"
      when: airdrop_result is defined and airdrop_result.rc != 0
